### ISSUE TITLE
Map001 - Witch one?

### ISSUE THREAD

**Issue by Antielfi** [TwinDragon/cornelica-translation#2]
Map Name
コルネリカ - Cornelica

Row 148: ツキウツシの花を手に入れた！

Final Suggestion:
I got a flower of Tsukushushi! |or| The flower of [tsukiutsushi] was obtained. 

Some work done for check using Google, Atlas, Mecab and JParser

	ツキウツシ		Tsukushi | [Tsukiutsushi]

	の	of

	花	flower

	を	to, indicates direct object of action, subject of causative expression, wtf in other term!

	手		hand, possession

	に		into

	入れ		to put
	
	た		It was, past completed or action
	
	|or|
	
	手に入れた	I got | it obtained it

**Comment by TwinDragon** [comment]
Maybe instead of something more literal, what about taking a liberty with something like... `I obtained the Tsukushushi flower!` perhaps? Just a thought.

**Comment by Antielfi** [comment]
Ok, lurking around the destroyed map I found the event. Is a chest you open and find the flower.
Now only remain to decide the form used for "item found" event

![ev143](https://user-images.githubusercontent.com/38109791/38387810-6c543db6-3919-11e8-86fc-0e196d040ecf.jpg)

**Comment by XenoPi** [comment]
`XXXXX obtained!` should work. Also the flower's name should probably be along the lines of "Moon flower" or "Moon's image flower".

**Comment by TwinDragon** [comment]
I'll have to see what @Darkhawkzer02 and @Bezerkerr have to say. I'm fine with either really. Though I am a bit partial to something like `I obtained the Moon Flower!` maybe.. That could work.

One of those things that is better to localize than to be literal with Japanese. lol

**Comment by Antielfi** [comment]
Item.json - Row 23- Item ID 21
夜にしか咲かない、青く輝く花。- Blooming flowers that only bloom at night

It's named in 027_01 (npc tell you where to find it)
It's named in itemMesse004 and here is a match with the .json map ツキウツシの花を手に入れた！
Funny....
