### ISSUE TITLE
Opinion on a line or two

### ISSUE THREAD

**Issue by TwinDragon** [TwinDragon/cornelica-translation#22]
Going through one of these PR's and I'm going to take a good chunk of it and commit myself while I wait for some opinions on a line or two.

Previous line for context:

```
[Justina]"Oh, if it isn't Lily, hehe, you're with a boy, \nare you on a date?"

Original: [リリィ]「ア、アルはそんなんじゃないよ！」
[Lily]"Al isn't like that!"
```
I said this in the relevant PR about it:

This is just a copy/paste of the bit I suggested:

`ア、アルはそんなんじゃないよ！`

I see its put as `Al isn't like that!` - but I wonder if it'd make more sense as something like `No, it isn't like that!` maybe. But me, I'm just guessing. Google failed me again on that line somewhat.

This same line appears in 014_03a as well, so some more opinions may not hurt about it.

**Comment by Antielfi** [comment]
Re-posting: All the shopkeeper allude to the idea that Al is the boyfriend/slave of Lily. Is the typical scene where a girl decide to help a boy and all around they assumed they are a new-born couple. Someone jokes about Lily is becoming adult... so is the classic bit played in every location to tell the classic joke (love those cringy scene).

Said that, `Ah, nono is not like that!!` > `No, It's not like that!` > `Ah, nono! Al is not that!!` 
From the most suited to for Lily to less... suited? On my opinion.

**Comment by XenoPi** [comment]
```[Justina]"Oh, if it isn't Lily. Fufu, And you brought a boy,\nare you on a date, perhaps?"

[Lily]"Th- That's not how I am with Al!"```
