### ISSUE TITLE
Don't forget about this one line!

### ISSUE THREAD

**Issue by Antielfi** [TwinDragon/cornelica-translation#27]
It's bugging me because we didn't even put the \n e.e
https://github.com/TwinDragon/cornelica-translation/blob/f6f27c419ed017adfa36af9b2dd9a8810b0f16a9/Cornelica/scenario/011.txt#L84-L86

**Comment by XenoPi** [comment]
`[Lily]"If this happens, 'on that day, you may not be able to act\nfor the rest of the day'... It looks like you're\nalready unable to act today, huh."`
