### ISSUE TITLE
We need someone with PS skill

### ISSUE THREAD

**Issue by Antielfi** [TwinDragon/cornelica-translation#56]
So I find a way to work around the encryption for the img.
Since we **only** want to TL, I keeped only the img with text that need a TL.
I'm not skilled with font and PS more in general, but I can provide the image to someone else

Here I put an example file. All image use transparency and layering for merge ingame, and there are 2-3 different font from what I can tell.

![mapname30](https://user-images.githubusercontent.com/38109791/38976132-968f0286-43b0-11e8-95aa-71ada64d73d2.png)

We can help with the TL part, since 90% of the work is already done probably in some scenario or map file. Just let me now!

**Comment by XenoPi** [comment]
Took a crack at it, could use a different font if needed.
![dungeon](https://user-images.githubusercontent.com/38111685/39079454-954811f2-44e0-11e8-99d3-c416d40179dd.png)

**Comment by TwinDragon** [comment]
Hm, I like it so far. Similar style as the original at least; doesn't have to be perfect.

**Comment by XenoPi** [comment]
Gonna try to get back on this... 
Aside from M-bg.png which could use an actual redrawer, though I have a rough solution, the rest I can do.

Let me know if these will work in-game after conversion.

img\pictures\tutorial6.png
![tutorial7](https://user-images.githubusercontent.com/38111685/45595996-9a428700-b97a-11e8-959a-e137f7d9921d.png)

img\pictures\tutorial7.png
![tutorial6](https://user-images.githubusercontent.com/38111685/45595990-7f701280-b97a-11e8-9b8a-3d619fdf8fec.png)

img\system\speak.png
![speak](https://user-images.githubusercontent.com/38111685/45596004-afb7b100-b97a-11e8-820d-86ef5e991056.png)

**Comment by Antielfi** [comment]
I lost a bit of time to get my magic touch back, but the transparency seems good and the final result blend well. M-bg can stay that way for now, it's not important at the moment...

**Comment by XenoPi** [comment]
Translated images, still need conversion for rpgmaker. I used Antielfi's edit for M-bg.png, but added the glyph back, which looks better than what I did, I think.

[translated.zip](https://github.com/TwinDragon/cornelica-translation/files/2405587/translated.zip)

**Comment by Antielfi** [comment]
Re-Encrypt and pushed up, I will look into those some time later today, in-game
