### ISSUE TITLE
Scenario Txt Original

### ISSUE THREAD

**Issue by Antielfi** [TwinDragon/cornelica-translation#59]
Since I'm editing and pushing over the cut in the repository, and since I have almost delete my original, I'll put fresh one here. It's not a big deal re-extract those from the .sl but it can be a pain
[scenario_txt.zip](https://github.com/TwinDragon/cornelica-translation/files/1959997/scenario_txt.zip)

**Comment by jetalpha** [comment]
i am new (no good english) so i dont know where i can write for a question

i see the story, its finish but all scene scene , hmm 20% full?

i have see something with the original japanese scenario ( .sl , it have see 614 file ) and in english scenerio ( .txt , it see  599 file )

take your time, but answer my question   -->   its stopped ? on break ? finished? In progress ? after 1 month 

thx you

**Comment by Antielfi** [comment]
The txt are less on git because we skip some engine one.

The story is or must be completed. The img file are still in jp so some onscreen stuff is still original.

We should miss only the H scene... mainly because is a specific skill that can't be helped with machine TL... and I'm not too good with english too (i'm italian).

Now that I'm thinking some specific npcs are still in jp because their way to talk is not standard and machine TL isn't helpfull either.

I'm still trying to push the project on my own but I must learn playing other TL game and the process isn't easy been a side project.

If someone have the skill or some good will, the door are open

**Comment by jetalpha** [comment]
ok, thanks you for the information, at least, I have my answers, good luck for your project

I looked for the 15 files that was missing, like his, you do not have to search

_MoveMode.sl
_CameraMode.sl
cglist.sl
change_left.sl
change_right.sl
mob008a.sl
mob009.sl
mob011a.sl
pash_000.sl
replay.sl
replay02.sl
replay03.sl
rplist.sl
sysFadeIn.sl
sysFadeOut.sl


byby, good evening and good luck ^_^

**Comment by Blue7x** [comment]
So how exactly do I extract the files to play the game in English, sorry I don't really know anything about coding. I just kinda want to play the game in English even if only partial.

**Comment by Antielfi** [comment]
Fixed the repository and add a mini-guide for the installation for this "Beta" version here (#60).
We will re-encrypt all file and create a simplier copy-pasta script when the game is 100% TL
