### ISSUE TITLE
Verna buged

### ISSUE THREAD

**Issue by Surothedeath** [TwinDragon/cornelica-translation#62]
i have experience a bug then you have lost against the lord you are supose to make of your own. and if i talk to verna i have 3 options and 2 of them are bugedr if i chose "were do i found the flower" i dont get a answe only she is in my screen but i can walk around same with secand option and the third is the porn sceen and then she is on my screen she dont disapear of i dont restart the game or reload

**Comment by Antielfi** [comment]
Can you upload the closest savefile? It's probably a syntax error in a script that was corrupted while being translated but with a closest save I can test it out faster

**Comment by Antielfi** [comment]
The last push should fix it. You can download the single file [Cornelica/scenario/027_01.txt] (https://github.com/TwinDragon/cornelica-translation/blob/master/Cornelica/scenario/027_01.txt) for a fast fix!
I won't lock the issue, I'm just closing it.

**Comment by Surothedeath** [comment]
sorry i have no save file ther i am past it
