### ISSUE TITLE
We want more space! - Proposition

### ISSUE THREAD

**Issue by Antielfi** [TwinDragon/cornelica-translation#9]
The length limit in the textbox is killing my feelings
I found the value limit in the TS_ADVsystem.js
```
row 120    //this.VIEW_TEXT_NUM = 27;
row 121     this.VIEW_TEXT_NUM = 31;
```
Using the .txt edit you can actually edit and reload fast enough to work with eye more then counting.
If you reload a save just outside the .txt you are editing, you can actually do a hotswap!

A lot a textboxs already translated suffer for little-to-none space, just waiting for your vote.
Vote for them, vote for more space!

**Comment by TwinDragon** [comment]
Hm, just wondering, what does that do?

**Comment by XenoPi** [comment]
It's the count of characters displayed on a single line, and you get two lines per text box. It cuts off in the middle of a word on the first two lines, and going over the limit of the third pushes the first line up and out of sight(?) I think.
  It looks like ~55 would be a nice amount, 60 would make TL a little easier and 62 would be pushing it.
  By the way, leaving a space like this `[Lily] "abc"` between the bracket and quotation mark seems to eat a character on each line, unnecessarily.

**Comment by Antielfi** [comment]
Yes, the third line override the previous two so you need another textbox considering the text go very fast.
The space thing probably is cause by the script translation in the infamus .js... But it's seems a lot of work touching it so is better keep an eye when scripting :D
If no one spot a problem we can try doing some fitting with 60 with the current translation so we can actually start both testing/playing the game and try to find more "natural" phrasing

**Comment by XenoPi** [comment]
It looks like the original gets three lines, it's weird that it only gets two if it's switched to English...

**Comment by TwinDragon** [comment]
Well, I'm not opposed to making the necessary changes if it'll make things easier in the long run.

**Comment by Antielfi** [comment]
There is both height and font size settings. I'm 90% sure that the plugin use a preview window, like many other, so they probably made a strict fit manually.
Probably the japanese style is slightly lower or with lower frame so rpg maker can actually fit 3 row instead of 2

**Comment by XenoPi** [comment]
I'd like to also blame it on that space `] "`, because font size doesn't change between kanji and english, and can't think of any other reason. If it's not that, dropping the font size by a point or two should work.

**Comment by Antielfi** [comment]
Since " is in the output i think that the script simply cut after the ] and put everything else in the text bit.
For the font size I can try to play later in the day

**Comment by Antielfi** [comment]
I'm playing using `120` so I can spot and cut better the sentence.
I don't know what @XenoPi are using at the moment but if we decide a value I can PR the file and close the .js modding for good (since they break the game if done wrong or too much)

**Comment by TwinDragon** [comment]
I recall seeing a commit for this, just can't find it. I'm going to consider this closed for now since it did change the value to 120.
